
name: use action to run shell command

on: [push]

jobs:
  run-shell-uses:
   runs-on: ubuntu-latest
   steps:
     - name: echo string
       id: echo-string
       uses: actions/echo@v1 # use uses to run action from any repository
       with: # use with to pass parameter to action
          message: "Hello World"
          color: "red"
     - name: multiple commands
       run: | # use pipe to run multiple commands
         echo {{steps.echo-string.output.message}}