
name: use action to run shell command

on: 
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run-shell-uses:
   runs-on: ubuntu-latest
   steps:
     - name: echo string
       id: echo-string
       uses: actions/hello-world-javascript-action@v1.1 # use uses to run action from any repository
       with: # use with to pass parameter to action
          who-to-greet: "i99dev"
          color: "red"
     - name: multiple commands
       run: | # use pipe to run multiple commands
         echo "${{steps.echo-string.outputs.time}}"