# name -> use for unieq name of workflow
name: shell workflow

# on -> run workflow on specific event, now i select push event for all brnaches
on: [push]

# if want for specific branch, use
# on: [push]
# branches:
# - master

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello World"
      - name: multiple commands
        run: | # use pipe to run multiple commands
          node -v
          npm -v
          echo "Hello World"
      - name: install python3
        run: |
          sudo apt-get update
          sudo apt-get install python3
      - name: run python script
        run: |
          import sys
          print(platform.processor())
        shell: python3